name:                aql
version:             0.1.0.0
github:              "statebox/aql"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aql#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- megaparsec
- QuickCheck
- scientific
- semigroups
- term-rewriting
- tabular
- wai
- wai-extra

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

executables:
  aql-exe:
    main:                Main.hs
    source-dirs:         cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aql
  aql-http:
    main:                Main.hs
    source-dirs:         http
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aql

tests:
  aql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aql
    - hspec
    - QuickCheck
