name:                aql-http
version:             0.1.0.0
github:              "statebox/aql"
license:             BSD3
author:              "Statebox"
copyright:           "2018 Statebox"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aql#readme>

dependencies:
- aql
- base >= 4.7 && < 5
- servant-server
- wai
- wai-extra
- warp

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror

executables:
  aql-http:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aql-http
